---

- hosts: localhost
  become: true

  vars_files:
    - "base-vars.yml"

  pre_tasks:
    - name: Set hostname
      hostname: "name={{ lookup('env', 'VM_HOSTNAME') }}"

    - name: "Build hosts file"
      lineinfile:
        dest: /etc/hosts
        line: "{{ item.key }} {{ item.value }}"
        state: present
      with_dict: "{{ vms_hosts|default({}) }}"

